class internal_server_error_exception(Exception):
    pass